---
booktitle: Proceedings of The 2nd International Conference on Predictive APIs and
  Apps
shortname: PAPIs 2015
year: '2016'
volume: 50
published: 2016-06-05
start: 2015-08-06
end: 2015-08-07
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: PAPIs-2015
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Louis
  family: Dorard
- given: Mark D.
  family: Reid
- given: Francisco J.
  family: Martin
description: |
  Proceedings of The 2nd International Conference on Predictive APIs and Apps
    Held in Sydney, Australia on 6-07 August 2015

  Published as Volume 50 by the Proceedings of Machine Learning Research on 05 June 2016.

  Volume Edited by:
    Louis Dorard
    Mark D. Reid
    Francisco J. Martin

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 6--07 Aug
url: http://proceedings.mlr.press
baseurl: "/v50"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v50
bibtex_copy: true
email: ''
conference:
  name: Conference on Predictive APIs and Apps
  url: http://www.papis.io/2015/
  location: Sydney, Australia
  dates:
  - 2015-08-06
  - 2015-08-07
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v50.bib
