---
booktitle: Proceedings of The 2nd International Conference on Predictive APIs and
  Apps
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: PAPIs 2015
year: '2016'
volume: 50
published: 2016-06-05
start: 2015-08-06
end: 2015-08-07
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: PAPIs-2015
month: 0
cycles: false
editor:
- given: Louis
  family: Dorard
- given: Mark D.
  family: Reid
- given: Francisco J.
  family: Martin
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 2nd International Conference on Predictive APIs and Apps
    Held in Sydney, Australia on 06-07 August 2015

  Published as Volume 50 by the Proceedings of Machine Learning Research on 05 June 2016.

  Volume Edited by:
    Louis Dorard
    Mark D. Reid
    Francisco J. Martin

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 06--07 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v50"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
permalink: "/:title.html"
ghub:
  edit: true
  repository: v50
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Conference on Predictive APIs and Apps
  url: http://www.papis.io/2015/
  location: Sydney, Australia
  dates:
  - 2015-08-06
  - 2015-08-07
  number: 2
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
